---
# Run via ansible-playbook -i <inventory> deploy.yml --extra-vars "@/creds/<vault>.yml" --ask-vault-pass --private-key=<private-key-path>
# Use tags to control which tasks run:
#   --tags "light" - Install lightweight tools and configs
#   --tags "heavy" - Install resource-intensive tools
#   --tags "zsh,tmux" - Install specific tools only
#   --skip-tags "heavy" - Install everything except heavy tools
# By default (no tags specified), all tasks will run
- name: Setup Development Environment
  hosts: all
  vars:
    # THE PASSED VAULT WILL NEED THE FOLLOWING VARIABLES:
    ansible_user: "{{ vault_ansible_user }}"
    ansible_sudo_pass: "{{ vault_sudo_pass }}"


  tasks:

    ### REQUIRED START ###
    - name: Ensure git is installed
      become: yes
      ansible.builtin.package:
        name: git
        state: present
      tags:
        - always

    - name: Ensure curl is installed
      become: yes
      ansible.builtin.package:
        name: curl
        state: present
      tags:
        - always

    - name: Clone koby-dev-env repository
      ansible.builtin.git:
        repo: https://github.com/KobyW/koby-dev-env
        dest: "/home/{{ ansible_user }}/koby-dev-env"
        version: main
        update: no
      tags:
        - always

    - name: Sync koby-dev-env repository
      ansible.builtin.git:
        repo: https://github.com/KobyW/koby-dev-env
        dest: "/home/{{ ansible_user }}/koby-dev-env"
        version: main
        update: yes
      tags:
        - never
        - sync

    - name: Install pip
      become: yes
      ansible.builtin.package:
        name: python3-pip
        state: present
      tags:
        - always

    - name: Ensure build-essential is installed
      become: yes
      ansible.builtin.package:
        name: build-essential
        state: present
      tags:
        - always

    - name: Ensure net-tools is installed
      become: yes
      ansible.builtin.package:
        name: net-tools
        state: present
      tags:
        - always

    - name: Ensure nmap is installed
      become: yes
      ansible.builtin.package:
        name: nmap
        state: present
      tags:
        - always

    - name: Install unzip
      become: yes
      ansible.builtin.package:
        name: unzip
        state: present
      tags:
        - always
    ### REQUIRED END ###


    ### LIGHT MISC START ###
    - name: Install bat
      become: yes
      ansible.builtin.package:
        name: bat
        state: present
      tags:
        - light
        - bat

    - name: Install zoxide
      ansible.builtin.shell: curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
      args:
        creates: "/home/{{ ansible_user }}/.local/bin/zoxide"
      tags:
        - light
        - zoxide

    - name: Install fzf
      become: yes
      ansible.builtin.package:
        name: fzf
        state: present
      tags:
        - light
        - fzf

    - name: Install expect
      become: yes
      ansible.builtin.package:
        name: expect
        state: present
      tags:
        - light
        - expect

    - name: Install wget
      become: yes
      ansible.builtin.package:
        name: wget
        state: present
      tags:
        - light
        - wget
    ### LIGHT MISC END ###


    ### ZSH START ###
    - name: Install zsh
      become: yes
      ansible.builtin.package:
        name: zsh
        state: present
      tags:
        - light
        - zsh

    - name: Check if Oh My Zsh is installed
      ansible.builtin.stat:
        path: "/home/{{ ansible_user }}/.oh-my-zsh"
      register: oh_my_zsh_installed
      tags:
        - light
        - zsh
        - oh-my-zsh

    - name: Install Oh My Zsh
      ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      when: 
        - not oh_my_zsh_installed.stat.exists
      tags:
        - light
        - zsh
        - oh-my-zsh

    - name: Install zsh-autosuggestions
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: "/home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        update: no
      tags:
        - light
        - zsh
        - zsh-autosuggestions

    - name: Copy .zshrc to home directory
      block:

        - name: Backup existing .zshrc
          ansible.builtin.copy:
            src: "/home/{{ ansible_user }}/.zshrc"
            dest: "/home/{{ ansible_user }}/.zshrc.bak"
            remote_src: yes
          ignore_errors: yes

        - name: Link .zshrc
          ansible.builtin.file:
            src: "/home/{{ ansible_user }}/koby-dev-env/configs/zshrc"
            dest: "/home/{{ ansible_user }}/.zshrc"
            state: link
            force: yes

      tags:
        - light
        - zsh
        - zshrc-copy

    - name: Ensure zsh is the default shell
      become: yes
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: /bin/zsh
      tags:
        - light
        - zsh
        - zsh-shell

    - name: Export SHELL environment variable
      ansible.builtin.lineinfile:
        path: "/home/{{ ansible_user }}/.bashrc"
        line: 'export SHELL=/bin/zsh'
        create: yes
      tags:
        - light
        - zsh
        - zsh-shell
    ### ZSH END ###


    ### P10k START ###
    - name: Install P10K
      block:

        - name: Clone Powerlevel10k repository
          ansible.builtin.git:
            repo: 'https://github.com/romkatv/powerlevel10k.git'
              #dest: "/home/{{ ansible_user }}/.oh-my-zsh/custom/themes/powerlevel10k"
            dest: "/home/{{ ansible_user }}/powerlevel10k"
            depth: 1

        - name: Backup existing p10k.zsh
          ansible.builtin.copy:
            src: "/home/{{ ansible_user }}/.p10k.zsh"
            dest: "/home/{{ ansible_user }}/.p10k.zsh.bak"
            remote_src: yes
          ignore_errors: yes

        - name: Link p10k.zsh
          ansible.builtin.file:
            src: "/home/{{ ansible_user }}/koby-dev-env/configs/p10k.zsh"
            dest: "/home/{{ ansible_user }}/.p10k.zsh"
            state: link
            force: yes

      tags:
        - light
        - p10k
    ### P10k END ###


    ### NeoVim START ###
    - name: Check if Neovim is installed
      ansible.builtin.stat:
        path: "/home/{{ ansible_user }}/.local/bin/nvim"
      register: neovim_installed
      tags:
        - light
        - neovim

    - name: Install Neovim v0.9.5
      block:

        - name: Ensure /usr/.local/bin directory exists
          ansible.builtin.file:
            path: "/home/{{ ansible_user }}/.local/bin"
            state: directory
            mode: '0755'

        - name: Download Neovim
          ansible.builtin.get_url:
            url: https://github.com/neovim/neovim/releases/download/v0.9.5/nvim-linux64.tar.gz
            dest: /tmp/nvim-linux64.tar.gz

        - name: Extract Neovim
          become: yes
          ansible.builtin.unarchive:
            src: /tmp/nvim-linux64.tar.gz
            dest: "/home/{{ ansible_user }}/.local/bin/"
            remote_src: yes

        - name: Remove Neovim archive
          ansible.builtin.file:
            path: /tmp/nvim-linux64.tar.gz
            state: absent

        - name: Link Neovim to /usr/local/bin
          become: yes
          ansible.builtin.file:
            src: "/home/{{ ansible_user }}/.local/bin/nvim-linux64/bin/nvim"
            dest: "/usr/local/bin/nvim"
            state: link
            force: yes

        - name: Ensure NeoVim is exported to PATH via zshrc
          become: yes
          ansible.builtin.lineinfile:
            path: "/home/{{ ansible_user }}/.zshrc"
            line: 'export PATH="/usr/local/nvim-linux64/bin:$PATH"'

      when: 
        - not neovim_installed.stat.exists
      tags:
        - light
        - neovim
    ### NeoVim END ###


    ### LunarVim START ###
    - name: Check if LunarVim is installed
      ansible.builtin.stat:
        path: "/home/{{ ansible_user }}/.local/bin/lvim"
      register: lunarvim_installed
      tags:
        - light
        - lunarvim
        - lvim

    - name: Install LunarVim
      block:
        - name: Download and install LunarVim
          ansible.builtin.shell: |
            curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.4/neovim-0.9/utils/installer/install.sh | bash -s -- --no-install-dependencies
          environment:
            LV_BRANCH: "release-1.4/neovim-0.9"
          args:
            creates: "/home/{{ ansible_user }}/.local/bin/lvim"

      when: 
        - not lunarvim_installed.stat.exists
      tags:
        - light
        - lunarvim
        - lvim

    - name: Deploy LunarVim configuration
      block:
        - name: Ensure LunarVim config directory exists
          ansible.builtin.file:
            path: "/home/{{ ansible_user }}/.config/lvim"
            state: directory
            mode: '0755'

        - name: Backup existing config.lua
          ansible.builtin.copy:
            src: "/home/{{ ansible_user }}/.config/lvim/config.lua"
            dest: "/home/{{ ansible_user }}/.config/lvim/config.lua.bak"
            remote_src: yes
          ignore_errors: yes

        - name: Link LunarVim config
          ansible.builtin.file:
            src: "/home/{{ ansible_user }}/koby-dev-env/configs/LVIMconfig.lua"
            dest: "/home/{{ ansible_user }}/.config/lvim/config.lua"
            state: link
            force: yes

        - name: Ensure custom lua modules directory exists
          ansible.builtin.file:
            path: "/home/{{ ansible_user }}/.config/lvim/lua"
            state: directory
            mode: '0755'

        - name: Link lua/koby directory
          ansible.builtin.file:
            src: "/home/{{ ansible_user }}/koby-dev-env/configs/lua/koby"
            dest: "/home/{{ ansible_user }}/.config/lvim/lua/koby"
            state: link
            force: yes

      tags:
        - light
        - lunarvim
        - lvim
        - lvim-config
    ### LunarVim END ###


    ### TMUX START ###
    - name: Install tmux
      become: yes
      ansible.builtin.package:
        name: tmux
        state: present
      tags:
        - light
        - tmux

    - name: Install tpm (tmux plugin manager)
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "/home/{{ ansible_user }}/.tmux/plugins/tpm"
        update: no
      tags:
        - light
        - tmux
        - tpm

    - name: Copy .tmux.conf to home directory
      block:
        - name: Backup existing .tmux.conf
          ansible.builtin.copy:
            src: "/home/{{ ansible_user }}/.tmux.conf"
            dest: "/home/{{ ansible_user }}/.tmux.conf.bak"
            remote_src: yes
          ignore_errors: yes
        - name: Link .tmux.conf
          ansible.builtin.file:
            src: "/home/{{ ansible_user }}/koby-dev-env/configs/tmux.conf"
            dest: "/home/{{ ansible_user }}/.tmux.conf"
            state: link
            force: yes
      tags:
        - light
        - tmux
        - tmux-copy
    ### TMUX END ###


    ### PFETCH START ###
    - name: Check if pfetch is installed
      ansible.builtin.stat:
        path: /usr/local/bin/pfetch
      register: pfetch_installed
      tags:
        - light
        - pfetch

    - name: Install pfetch
      block:

        - name: Download pfetch
          ansible.builtin.get_url:
            url: https://github.com/dylanaraps/pfetch/archive/master.zip
            dest: /tmp/pfetch-master.zip
        - name: Unzip pfetch
          ansible.builtin.unarchive:
            src: /tmp/pfetch-master.zip
            dest: /tmp/
            remote_src: yes
        - name: Install pfetch
          become: yes
          ansible.builtin.copy:
            src: /tmp/pfetch-master/pfetch
            dest: /usr/local/bin/pfetch
            mode: '0755'
            remote_src: yes
        - name: Clean up pfetch files
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - /tmp/pfetch-master.zip
            - /tmp/pfetch-master

      when: 
        - not pfetch_installed.stat.exists
      tags:
        - light
        - pfetch
    ### PFETCH END ###


    ### LAZY TOOLING START ###
    - name: Install Lazydocker
      ansible.builtin.shell: curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
      args:
        creates: /usr/local/bin/lazydocker
      tags:
        - light
        - lazydocker

    - name: Check if Lazygit is installed
      ansible.builtin.stat:
        path: /usr/local/bin/lazygit
      register: lazygit_installed
      tags:
        - light
        - lazygit

    - name: Install Lazygit
      block:
        
        - name: Download Lazygit
          ansible.builtin.get_url:
            url: "https://github.com/jesseduffield/lazygit/releases/download/v0.43.1/lazygit_0.43.1_Linux_x86_64.tar.gz"
            dest: /tmp/lazygit.tar.gz
        - name: Extract Lazygit
          ansible.builtin.unarchive:
            src: /tmp/lazygit.tar.gz
            dest: /tmp/
            remote_src: yes
        - name: Install Lazygit
          become: yes
          ansible.builtin.copy:
            src: /tmp/lazygit
            dest: /usr/local/bin/lazygit
            mode: '0755'
            remote_src: yes
        - name: Clean up Lazygit files
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - /tmp/lazygit.tar.gz
            - /tmp/lazygit

      when: 
        - not lazygit_installed.stat.exists
      tags:
        - light
        - lazygit
    ### LAZY TOOLING END ###


    ### MISC HEAVY START ###
    - name: Install cargo
      ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      args:
        creates: "/home/{{ ansible_user }}/.cargo/bin/cargo"
      tags:
        - heavy
        - cargo

        #    - name: Install jc
        #      become: yes
        #      ansible.builtin.pip:
        #        name: jc
        #        state: present
        #      tags:
        #        - heavy
        #        - jc
        #
        #    - name: Install jq
        #      become: yes
        #      ansible.builtin.package:
        #        name: jq
        #        state: present
        #      tags:
        #        - heavy
        #        - jq

    - name: Install docker.io
      become: yes
      ansible.builtin.package:
        name: docker.io
        state: present
      tags:
        - heavy
        - docker

    # - name: Install docker compose plugin
    #   become: yes
    #   ansible.builtin.package:
    #     name: docker-compose-plugin
    #     state: present
    #   tags:
    #     - heavy
    #     - docker
    #     - docker-compose

    - name: Install npm
      become: yes
      ansible.builtin.package:
        name: npm
        state: present
      tags:
        - heavy
        - npm
    ### MISC HEAVY END ###