# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

clear

# Define color codes
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[0;37m'

BRIGHT_BLACK='\033[1;30m'
BRIGHT_RED='\033[1;31m'
BRIGHT_GREEN='\033[1;32m'
BRIGHT_YELLOW='\033[1;33m'
BRIGHT_BLUE='\033[1;34m'
BRIGHT_MAGENTA='\033[1;35m'
BRIGHT_CYAN='\033[1;36m'
BRIGHT_WHITE='\033[1;37m'

BG_BLACK='\033[40m'
BG_RED='\033[41m'
BG_GREEN='\033[42m'
BG_YELLOW='\033[43m'
BG_BLUE='\033[44m'
BG_MAGENTA='\033[45m'
BG_CYAN='\033[46m'
BG_WHITE='\033[47m'

NC='\033[0m' # No Color

echo -e "${GREEN}LOADING ZSHRC..${NC}"

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)

# Note to self: run this command to install zsh autosuggestion plugin:
# git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
plugins=(git docker zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# User configuration

alias zshconfig="vi ~/.zshrc"
alias ohmyzsh="vi ~/.oh-my-zsh"
source ~/powerlevel10k/powerlevel10k.zsh-theme

##### Personal additions - koby #####

## MISC ##
export today=$(date +%Y-%m-%d)
export currentTime=$(date +%Y-%m-%d:%H:%M:%S)

export TERM="xterm-256color"
export COLORTERM="truecolor"

# Edit machine-specific zshrc
edit-machine-specific(){
  if [ -f "$HOME/koby-dev-env/env/zsh-machine-specific.zshrc" ]; then
    vim $HOME/koby-dev-env/env/zsh-machine-specific.zshrc
  else
    echo -e "${YELLOW}Initial edit detected, creating zsh-machine-specific.zshr${NC}"
    sleep 2
    cp $HOME/koby-dev-env/env/zsh-machine-specific.zshrc $HOME/koby-dev-env/env/zsh-machine-specific.zshrc.bk-${today} 2> /dev/null
    cp $HOME/koby-dev-env/env/zsh-machine-specific.example $HOME/koby-dev-env/env/zsh-machine-specific.zshrc
    vim $HOME/koby-dev-env/env/zsh-machine-specific.zshrc
  fi
}
alias ezm=edit-machine-specific
alias esm=edit-machine-specific

echo -e "${BLUE}Loading misc exports and aliases..${NC}"

export EDITOR='vim'
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.local/nvim-linux64/bin:$PATH
alias vim="lvim"

alias xc="xclip -selection clipboard"
alias xp="xclip -selection clipboard -o"

alias dev="git checkout dev"
alias stage="git checkout stage"
alias main="git checkout main"

HISTSIZE=10000
SAVEHIST=10000

alias remove-zi='find . -type f -name "*Zone.Identifier" -exec rm -v {} \;'
alias sz='source $HOME/.zshrc && echo -e "${YELLOW}Sourced $HOME/.zshrc${NC}"'
alias ez='vim $HOME/.zshrc'
alias ezvi='vi $HOME/.zshrc'
alias zcat='cat $HOME/.zshrc'
alias explore='explorer.exe .'
alias ssh-agent-start='echo "eval \"\$(ssh-agent -s)\""; eval "$(ssh-agent -s)"'
alias cat="batcat --style=plain"
alias lunar-edit="vi ~/.config/lvim/config.lua"
alias lunar-edit-lvim="lvim ~/.config/lvim/config.lua"
alias tpm-install="rm -rf ~/.config/tmux/plugins/tmux && ~/.tmux/plugins/tpm/scripts/install_plugins.sh"
alias tmux-edit-home="vim ~/.tmux.conf"
alias tmux-reset="tmux kill-server; rm -rf /tmp/tmux-* && tpm-install"
alias tmux-restart="tmux kill-server; rm -rf /tmp/tmux-* && tpm-install"
alias sshls="ls $HOME/.ssh"
alias sshchmod="chmod 600 $HOME/.ssh/* && chmod 700 $HOME/.ssh"
alias lg="lazygit"

# Enable zoxide
#eval "$(zoxide init zsh)"
eval "$(zoxide init --cmd cd zsh)"
#alias cd='z'

bindkey '^N' autosuggest-accept

## SOURCING ALL ZSHRC FILES FROM SPECIFIED DIRS ##
echo -e "${BLUE}Sourcing additional zsh configs..${NC}"

# Enable extended globbing for better file matching
setopt EXTENDED_GLOB
setopt NULL_GLOB

# Define the directories to search for .zshrc files
zshrc_directories=(
    "$HOME/koby-dev-env/env"
    "$HOME/koby-dev-env/util/ssh"
)

alias claude-init="$HOME/koby-dev-env/util/claude-init.sh"

# Loop through each directory and source all .zshrc files
for dir in $zshrc_directories; do
    #echo -e "${YELLOW}Checking directory: $dir${NC}"
    for file in $dir/*.zshrc(N); do
        #echo -e "${GREEN}Found file: $file${NC}"
        if [[ -f "$file" ]]; then
            echo -e "${BRIGHT_GREEN}Sourcing file: $file${NC}"
            source "$file"
        fi
    done
done

# Unset the directories variable to clean up
unset zshrc_directories

# delay to check debug messages
# sleep 6

# pfetch configuration - disable package checking
export PF_INFO="ascii title os host kernel uptime memory"

clear
pfetch
HOSTNAME=$(hostname)
echo -e "${GREEN}HOST:${HOSTNAME} ${NC}"

##### END OF PERSONAL ADDITIONS #####

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="$HOME/.spin/bin:$PATH"

purge_path_duplicates() {
    export PATH=$(echo -n $PATH | awk -v RS=: -v ORS=: '!($0 in a) {a[$0]; print}' | sed 's/:$//')
}
purge_path_duplicates

# bun completions
[ -s "/home/woodk/.bun/_bun" ] && source "/home/woodk/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

alias claude="/home/woodk/.claude/local/claude"
