# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)

# Note to self: run this command to install zsh autosuggestion plugin:
# git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
plugins=(git docker zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# User configuration

alias zshconfig="vi ~/.zshrc"
alias ohmyzsh="vi ~/.oh-my-zsh"
source ~/powerlevel10k/powerlevel10k.zsh-theme

##### Personal additions - koby #####
clear
pfetch

## MISC ##
export EDITOR='lvim'
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.local/nvim-linux64/bin:$PATH
alias vim="lvim"
#alias vi="lvim"
alias nvim="lvim"

alias xc="xclip -selection clipboard"
alias xp="xclip -selection clipboard -o"

HISTSIZE=10000
SAVEHIST=10000

export today=$(date +%Y-%m-%d)
alias remove-zi='find . -type f -name "*Zone.Identifier" -exec rm -v {} \;'
#alias zsh-source-home='source ~/.zshrc && echo "Sourced ~/.zshrc"'
#alias zsh-edit-home='vi ~/.zshrc'
alias sz='source ~/.zshrc && echo "Sourced ~/.zshrc"'
alias ez='vim ~/.zshrc'
alias ezvi='vi ~/.zshrc'
alias explore='explorer.exe .'
alias ssh-agent-start='echo "eval \"\$(ssh-agent -s)\""; eval "$(ssh-agent -s)"'
alias cat="batcat --style=plain"
alias lunar-edit="vi ~/.config/lvim/config.lua"
alias lunar-edit-lvim="lvim ~/.config/lvim/config.lua"
alias tpm-install="rm -rf ~/.config/tmux/plugins/tmux ~/.tmux/plugins/tpm/scripts/install_plugins.sh"
alias tmux-edit-home="vim ~/.tmux.conf"
alias tmux-reset="tmux kill-server; rm -rf /tmp/tmux-* && tpm-install"
alias tmux-restart="tmux kill-server; rm -rf /tmp/tmux-* && tpm-install"
alias sshls="ls $HOME/.ssh"
alias sshchmod="chmod 600 $HOME/.ssh/* && chmod 700 $HOME/.ssh"
alias lg="lazygit"

# Enable zoxide
#eval "$(zoxide init zsh)"
eval "$(zoxide init --cmd cd zsh)"
#alias cd='z'

bindkey '^N' autosuggest-accept

# Enable extended globbing for better file matching
setopt EXTENDED_GLOB

# Define the directories to search for .zshrc files
zshrc_directories=(
    "$HOME/koby-dev-env/env/"
    "$HOME/koby-dev-env/util/"
)

# Loop through each directory and source all .zshrc files
for dir in $zshrc_directories; do
    for file in $dir/*.zshrc(N); do
        if [[ -f "$file" ]]; then
            source "$file"
        fi
    done
done

# Unset the directories variable to clean up
unset directories

##### END OF PERSONAL ADDITIONS #####

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
